---
managers: []
workers: []

env_managers: "{{ groups[env_name] | intersect(groups['manager']) | intersect(groups['catalystcloud']) | difference(groups['database'])  }}"
env_db_managers: "{{ groups[env_name] | intersect(groups['database']) }}"
env_workers: "{{ groups[env_name] | intersect(groups['worker']) }}"

primary_manager: "{{ groups['primary_manager'] | intersect(groups[env_name]) | first }}"

database_host: domaindb
rabbitmq_host: rabbitmq
rabbitmq_port: 5672
rabbitmq_default_vhost: /

registries:
  - nzrs
  - cocca
  - centralnic

images:
  rabbitmq:
    image: rabbitmq
    tag: 3.6-management-alpine
  domaindb:
    image: mysql
    tag: latest
  api:
    image: quay.io/heytrav/domain-api
    tag: 1.2.22
  nodepp:
    image: quay.io/heytrav/nodepp
    tag: 1.2.8
  nginx:
    image: nginx
    tag: stable-alpine
  memcached:
    image: memcached
    tag: alpine

cocca_command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "/cocca-epp.json", "-r", "cocca-test", "--loglevel", "debug"]
cocca_healthcheck: 
  test: ["CMD", "node", "./lib/healthcheck.js", "-j", "-f", "/cocca-epp.json", "-r", "cocca-test", "--loglevel", "debug"]
  interval: 1m
  timeout: 20s
  retries: 3
cocca_environment:
  EPP_LOGIN_FILE: /run/secrets/cocca_login
  EPP_PASSWORD_FILE: /run/secrets/cocca_password
  RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
  RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
  RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
  SENTRY_DSN_FILE: /run/secrets/nodepp_sentry_dsn
  RELEASE_VERSION: "{{ images.nodepp.tag  }}"
  RABBITMQ_HOST: "{{ rabbitmq_host  }}"
  RABBITMQ_PORT: "{{ rabbitmq_port  }}"
  RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_default_vhost  }}"
cocca_secrets:
  - cocca_login
  - cocca_password
  - nodepp_sentry_dsn
  - rabbitmq_default_user
  - rabbitmq_default_pass
  - rabbitmq_erlang_cookie

centralnic_command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "/centralnic-epp.json", "-r", "centralnic-test", "--loglevel", "debug"]
centralnic_healthcheck: 
  test: ["CMD", "node", "./lib/healthcheck.js", "-j", "-f", "/centralnic-epp.json", "-r", "centralnic-test", "--loglevel", "debug"]
  interval: 1m
  timeout: 20s
  retries: 3
centralnic_environment:
  EPP_LOGIN_FILE: /run/secrets/centralnic_login
  EPP_PASSWORD_FILE: /run/secrets/centralnic_password
  RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
  RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
  RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
  SENTRY_DSN_FILE: /run/secrets/nodepp_sentry_dsn
  RELEASE_VERSION: "{{ images.nodepp.tag  }}"
  RABBITMQ_HOST: "{{ rabbitmq_host  }}"
  RABBITMQ_PORT: "{{ rabbitmq_port  }}"
  RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_default_vhost  }}"
centralnic_secrets:
  - centralnic_login
  - centralnic_password
  - nodepp_sentry_dsn
  - rabbitmq_default_user
  - rabbitmq_default_pass
  - rabbitmq_erlang_cookie

nzrs_command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "/nzrs-epp.json", "-r", "nzrs-test", "--loglevel", "debug"]
nzrs_healthcheck: 
  test: ["CMD", "node", "./lib/healthcheck.js", "-j", "-f", "/nzrs-epp.json", "-r", "nzrs-test", "--loglevel", "debug"]
  interval: 1m
  timeout: 20s
  retries: 3
nzrs_environment:
  EPP_LOGIN_FILE: /run/secrets/nzrs_login
  EPP_PASSWORD_FILE: /run/secrets/nzrs_password
  RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
  RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
  RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
  SENTRY_DSN_FILE: /run/secrets/nodepp_sentry_dsn
  RELEASE_VERSION: "{{ images.nodepp.tag  }}"
  RABBITMQ_HOST: "{{ rabbitmq_host  }}"
  RABBITMQ_PORT: "{{ rabbitmq_port  }}"
  RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_default_vhost  }}"
nzrs_secrets:
  - nzrs_login
  - nzrs_password
  - nodepp_sentry_dsn
  - nzrs-epp.pem
  - nzrs-epp.key
  - rabbitmq_default_user
  - rabbitmq_default_pass
  - rabbitmq_erlang_cookie

rabbitmq_environment:
  RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
  RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
  RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
  RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.49
  RABBITMQ_HOST: "{{ rabbitmq_host  }}"
  RABBITMQ_PORT: "{{ rabbitmq_port  }}"
  RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_default_vhost  }}"
rabbitmq_secrets:
  - rabbitmq_default_user
  - rabbitmq_default_pass
  - rabbitmq_erlang_cookie

domaindb_environment:
  MYSQL_USER_FILE: /run/secrets/mysql_user
  MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
  MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
  MYSQL_DATABASE_FILE: /run/secrets/mysql_database
domaindb_secrets:
  - mysql_password
  - mysql_root_password
  - mysql_database
  - mysql_user

migrate_command: ["python3", "manage.py", "migrate"]

celery_command:
  - celery
  - -A
  - application
  - worker
  - -l
  - info
celery_environment:
  RELEASE_VERSION: "{{ images.api.tag  }}"
  RABBITMQ_HOST: "{{ rabbitmq_host  }}"
  RABBITMQ_PORT: "{{ rabbitmq_port  }}"
  RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_default_vhost  }}"
  SENTRY_ENVIRONMENT: "{{ sentry_environment }}"
  MYSQL_HOST: "{{ database_host  }}"
  RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
  RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
  RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
  SENTRY_DSN_FILE: /run/secrets/celery_sentry_dsn
  MYSQL_USER_FILE: /run/secrets/mysql_user
  MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
  MYSQL_DATABASE_FILE: /run/secrets/mysql_database
  DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
  JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
celery_secrets:
  - mysql_database
  - mysql_user
  - mysql_password
  - celery_sentry_dsn
  - django_secret_key
  - jwt_secret_key
  - rabbitmq_default_user
  - rabbitmq_default_pass
  - rabbitmq_erlang_cookie
celery_deploy:
  restart_policy:
      condition: on-failure
      delay: 10s

api_command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
api_environment:
  SENTRY_DSN_FILE: /run/secrets/domain_api_sentry_dsn
  MYSQL_USER_FILE: /run/secrets/mysql_user
  MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
  MYSQL_DATABASE_FILE: /run/secrets/mysql_database
  DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
  JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
  RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
  RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
  RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
  MYSQL_HOST: "{{ database_host  }}"
  RELEASE_VERSION: "{{ images.api.tag  }}"
  RABBITMQ_HOST: "{{ rabbitmq_host  }}"
  RABBITMQ_PORT: "{{ rabbitmq_port  }}"
  RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_default_vhost  }}"
  SENTRY_ENVIRONMENT: "{{ sentry_environment }}"
api_secrets:
  - mysql_database
  - mysql_user
  - mysql_password
  - domain_api_sentry_dsn
  - django_secret_key
  - jwt_secret_key
  - rabbitmq_default_user
  - rabbitmq_default_pass
  - rabbitmq_erlang_cookie
api_deploy:
  replicas: 1
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: pause
  restart_policy:
    condition: on-failure
    delay: 10s

nginx_secrets:
  - site.key
  - site.crt
nginx_ports: 
  - 443:443
nginx_deploy:
  restart_policy:
    condition: on-failure
    delay: 10s

memcached_deploy:
  restart_policy:
    condition: on-failure
    delay: 10s
  resources:
    limits:
      memory: 64M
    reservations:
      memory: 64M
        
docker_secrets:
  cocca_login:
    external: true
  cocca_password:
    external: true
  centralnic_login:
    external: true
  centralnic_password:
    external: true
  mysql_root_password:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  celery_sentry_dsn:
    external: true
  domain_api_sentry_dsn:
    external: true
  nodepp_sentry_dsn:
    external: true
  site.key:
    external: true
  site.crt:
    external: true
  django_secret_key:
    external: true
  jwt_secret_key:
    external: true
  nzrs_login:
    external: true
  nzrs_password:
    external: true
  nzrs-epp.pem:
    external: true
  nzrs-epp.key:
    external: true
  rabbitmq_default_user:
    external: true
  rabbitmq_default_pass:
    external: true
  rabbitmq_erlang_cookie:
    external: true

nodepp_sentry_webhook_url: "{{ vault_nodepp_sentry_webhook_url }}" 
api_sentry_webhook_url: "{{ vault_api_sentry_webhook_url }}"
celery_sentry_webhook_url: "{{ vault_celery_sentry_webhook_url }}"


configs:
  nginx:
    file: site.conf
    services:
      - nginx
    version: 1
    compose:
      target: /etc/nginx/conf.d/site.conf
