---
managers: []
workers: []

env_managers: "{{ groups[env_name] | intersect(groups['manager']) | intersect(groups['catalystcloud']) | difference(groups['database'])  }}"
env_db_managers: "{{ groups[env_name] | intersect(groups['database']) }}"
env_workers: "{{ groups[env_name] | intersect(groups['worker']) }}"

primary_manager: "{{ groups['primary_manager'] | intersect(groups[env_name]) | first }}"

database_host: domaindb
rabbitmq_host: rabbitmq
rabbitmq_port: 5672
rabbitmq_default_vhost: /

registries:
  - nzrs
  - cocca
  - centralnic


core_configs:
  nginx:
    file: site.conf
    services:
      - nginx
    version: 1
    compose:
      target: /etc/nginx/conf.d/site.conf

services: "{{ core_services | combine(epp_services, recursive=True) | combine(volumes, recursive=True) }}"
configs: "{{ core_configs | combine(epp_configs, recursive=True) }}"
secrets: "{{ core_secrets | combine(epp_secrets, recursive=True) }}"
service_secrets: "{{ services.values() | selectattr('secrets', 'defined') | sum(attribute='secrets', start=[]) |  unique | list  }}"
