---

database_host: domaindb
rabbitmq_host: rabbitmq
rabbitmq_port: 5672
rabbitmq_default_vhost: /

nodepp_sentry_webhook_url: vault_nodepp_sentry_webhook_url
api_sentry_webhook_url: vault_api_sentry_webhook_url
celery_sentry_webhook_url: vault_celery_sentry_webhook_url

docker_secrets:
  cocca_test_login:
    external: true
  cocca_test_password:
    external: true
  cocca_test_config:
    external: true
  centralnic_test_login:
    external: true
  centralnic_test_password:
    external: true
  centralnic_test_config:
    external: true
  mysql_root_password:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  celery_sentry_dsn:
    external: true
  domain_api_sentry_dsn:
    external: true
  nodepp_sentry_dsn:
    external: true
  site.key:
    external: true
  site.crt:
    external: true
  django_secret_key:
    external: true
  jwt_secret_key:
    external: true
  nzrs_test_login:
    external: true
  nzrs_test_password:
    external: true
  nzrs_test_config:
    external: true
  nzrs-epp-test.pem:
    external: true
  nzrs-epp-test.key:
    external: true
  logzio_token:
    external: true 
