---
cc_ssh_user: "{{ lookup('env', 'USER') }}"
base_directory: ~/workspace/innovation/compose-drs
sentry_environment: development

swarm_init_extra_args: "--advertise-addr {{ ansible_default_ipv6.address }}" 

api_image: "quay.io/heytrav/domain-api:{{ api_version }}"
api_version: 1.2.22
nodepp_image: "quay.io/heytrav/nodepp:{{ nodepp_version }}"
nodepp_version: 1.2.8

services_supplement:
  cocca: "{{ cocca }}"
  centralnic: "{{ centralnic }}"


volumes_supplement:
  api: 
    volumes: "{{ api_volumes }}"
  celery:
    volumes: "{{ api_volumes }}"
  migrate: 
    volumes: "{{ api_volumes }}"
  cocca: 
    volumes: "{{ nodepp_volumes }}"
  centralnic: 
    volumes: "{{ nodepp_volumes }}"
  domaindb:
    volumes:
      - ../database/mysql:/var/lib/mysql

  
api_volumes:
  - ../drs-project:/usr/local/domain-api

nodepp_volumes:
  - ../nodepp:/opt/project/node-epp
