---
ansible_python_interpreter: "/home/travis/workspace/catalystcloud-ansible/ansible-venv/bin/python"
cc_ssh_user: "{{ lookup('env', 'USER') }}"
base_directory: ~/workspace/innovation/compose-drs
sentry_environment: development

swarm_init_extra_args: "--advertise-addr {{ ansible_default_ipv6.address }}" 

registries:
  - cocca
  - centralnic

api_image: "quay.io/heytrav/domain-api:{{ api_version }}"
api_version: 1.2.22
nodepp_image: "quay.io/heytrav/nodepp:{{ nodepp_version }}"
nodepp_version: 1.2.8

epp_services:
  cocca: "{{ cocca_service }}"
  centralnic: "{{ centralnic_service }}"

epp_configs:
  cocca: "{{ cocca_config}}"
  centralnic: "{{ centralnic_config }}"

epp_secrets: "{{ {} | combine(cocca_secrets, recursive=True) | combine(centralnic_secrets, recursive=True) }}"

api_volumes:
  - ../drs-project:/usr/local/domain-api
nodepp_volumes:
  - ../nodepp:/opt/project/node-epp

volumes:
  api: 
    volumes: "{{ api_volumes }}"
  celery:
    volumes: "{{ api_volumes }}"
  migrate: 
    volumes: "{{ api_volumes }}"
  cocca: 
    volumes: "{{ nodepp_volumes }}"
  centralnic: 
    volumes: "{{ nodepp_volumes }}"
  domaindb:
    volumes:
      - ../database/mysql:/var/lib/mysql
