---

sentry_environment: development

services:
  rabbitmq: "{{ rabbitmq_service }}" 
  domaindb: "{{ domaindb_service }}" 
  nginx: "{{ nginx_service  }}"
  memcached: "{{ memcached_service  }}"
  migrate: "{{ migrate_service  }}"
  celery: "{{ celery_service  }}"
  api: "{{ api_service  }}"
  cocca: "{{ cocca_service  }}"
  centralnic: "{{ centralnic_service }}"

service_volumes:
  cocca:
    volumes:
      - ../nodepp:/opt/project/node-epp
  centralnic:
    volumes:
      - ../nodepp:/opt/project/node-epp
  domaindb:
    volumes:
      - ../database/mysql:/var/lib/mysql
  api:
    volumes:
      - ../drs-project:/usr/local/domain-api

cocca_deploy:
  replicas: 1
  restart_policy:
    condition: on-failure
    delay: 10s
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: pause
centralnic_deploy:
  replicas: 1
  restart_policy:
    condition: on-failure
    delay: 10s
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: pause
nzrs_deploy:
  replicas: 1
  restart_policy:
    condition: on-failure
    delay: 10s
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: pause

