---

base_directory: ~/workspace/innovation/compose-drs

nzrs: false
cocca: true
centralnic: false

centralnic_volumes:
  - ../nodepp:/opt/project/node-epp
cocca_volumes:
  - ../nodepp:/opt/project/node-epp

sentry_environment: guest-development

celery_sentry_dsn: vault_celery_sentry_dsn
domain_api_sentry_dsn: vault_domain_api_sentry_dsn
nodepp_sentry_dsn: vault_nodepp_sentry_dsn
django_secret_key: vault_django_secret_key
jwt_secret_key: vault_jwt_secret_key
logzio_token: vault_logzio_token
rabbitmq_default_user: vault_rabbitmq_default_user
rabbitmq_default_pass: vault_rabbitmq_default_pass
rabbitmq_erlang_cookie: vault_rabbitmq_erlang_cookie
cocca_login: vault_cocca_login
cocca_password: vault_cocca_password
mysql_user: vault_mysql_user
mysql_password: vault_mysql_password
mysql_database: vault_mysql_database
site_crt: vault_site_crt
site_key: vault_site_key
