---

base_directory: ~/workspace/innovation/compose-drs
sentry_environment: guest-development

services:
  rabbitmq: "{{ rabbitmq_service }}" 
  domaindb: "{{ domaindb_service }}" 
  nginx: "{{ nginx_service  }}"
  memcached: "{{ memcached_service  }}"
  migrate: "{{ migrate_service  }}"
  celery: "{{ celery_service  }}"
  api: "{{ api_service  }}"
  cocca: "{{ cocca_service  }}"

service_volumes:
  cocca:
    volumes:
      - ../nodepp:/opt/project/node-epp
  domaindb:
    volumes:
      - ../database/mysql:/var/lib/mysql
  api:
    volumes:
      - ../drs-project:/usr/local/domain-api
