---

base_directory: ~/workspace/innovation/compose-drs
images:
  rabbitmq:
    image: quay.io/heytrav/rabbitmq
    tag: latest
  mariadb:
    image: mysql
    tag: latest
  api:
    image: quay.io/heytrav/domain-api
    tag: 1.2.20
  nodepp:
    image: quay.io/heytrav/nodepp
    tag: 1.2.5
  nginx:
    image: quay.io/heytrav/drs-nginx
    tag: 0.1.0
  memcached:
    image: memcached
    tag: latest

service_list:
  rabbitmq:
    image: "{{ images.rabbitmq.image  }}:{{ images.rabbitmq.tag  }}"
    ports:
      - 15672:15672
    env_file: .stack_env

  domaindb:
    image: "{{ images.mariadb.image  }}:{{ images.mariadb.tag  }}"
    env_file: .stack_env
    ports:
      - 3306:3306
    secrets:
      - mysql_password
      - mysql_root_password
      - mysql_database
      - mysql_user
    volumes:
      - ../database/mysql:/var/lib/mysql
  celery:
    image: "{{ images.api.image  }}:{{ images.api.tag  }}"
    command: ["celery", "-A", "application", "worker", "-l", "info"]
    volumes:
      - ../drs-project:/usr/local/domain-api
    depends_on:
      - rabbitmq
    env_file: .stack_env
    environment:
      RELEASE_VERSION: "{{ images.api.tag  }}"
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
      - django_secret_key
      - jwt_secret_key
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  cocca:
    image: "{{ images.nodepp.image  }}:{{ images.nodepp.tag  }}"
    command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "/run/secrets/cocca_test_config", "-r", "cocca-test", "--loglevel", "debug"]
    volumes:
      - ../nodepp:/opt/project/node-epp
    healthcheck: 
      test: ["CMD", "node", "./lib/healthcheck.js", "-j", "-f", "/run/secrets/cocca_test_config", "-r", "cocca-test", "--loglevel", "debug"]
      interval: 1m
      timeout: 20s
      retries: 3
    depends_on:
      - rabbitmq
    env_file: .stack_env
    environment:
      EPP_LOGIN_FILE: /run/secrets/cocca_test_login
      EPP_PASSWORD_FILE: /run/secrets/cocca_test_password
      RELEASE_VERSION: "{{ images.nodepp.tag  }}"
    secrets:
      - cocca_test_login
      - cocca_test_password
      - cocca_test_config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: pause

  migrate:
    image: "{{ images.api.image  }}:{{ images.api.tag  }}"
    command: ["python3", "manage.py", "migrate"]
    volumes:
      - ../drs-project:/usr/local/domain-api
    depends_on:
      - domaindb
    env_file: .stack_env
    environment:
      RELEASE_VERSION: "{{ images.api.tag  }}"
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
      - django_secret_key
      - jwt_secret_key
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1

  api:
    image: "{{ images.api.image  }}:{{ images.api.tag  }}"
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    #command: ["gunicorn", "application.wsgi", "-w", "1", "-b", "0.0.0.0:8000"]
    volumes:
      - ../drs-project:/usr/local/domain-api
    depends_on:
      - rabbitmq
      - domaindb
    env_file: .stack_env
    environment:
      RELEASE_VERSION: "{{ images.api.tag  }}"
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
      - django_secret_key
      - jwt_secret_key
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
      restart_policy:
        condition: on-failure
        delay: 10s

  nginx:
    image: "{{ images.nginx.image  }}:{{ images.nginx.tag  }}"
    ports:
      - "443:443"
    secrets:
      - site.key
      - site.crt
    command: ["nginx"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  memcached:
    image: "{{ images.memcached.image  }}:{{ images.memcached.tag  }}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M

sentry_environment: guest-development

celery_sentry_dsn: vault_celery_sentry_dsn
domain_api_sentry_dsn: vault_domain_api_sentry_dsn
nodepp_sentry_dsn: vault_nodepp_sentry_dsn
django_secret_key: vault_django_secret_key
jwt_secret_key: vault_jwt_secret_key
logzio_token: vault_logzio_token
rabbitmq_default_user: vault_rabbitmq_default_user
rabbitmq_default_pass: vault_rabbitmq_default_pass
rabbitmq_erlang_cookie: vault_rabbitmq_erlang_cookie
cocca_login: vault_cocca_login
cocca_password: vault_cocca_password
mysql_user: vault_mysql_user
mysql_password: vault_mysql_password
mysql_database: vault_mysql_database
site_crt: vault_site_crt
site_key: vault_site_key
