version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    env_file: .env

  domaindb:
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ../database/mysql:/var/lib/mysql

  celery:
    image: quay.io/heytrav/domain-api:latest
    volumes:
      - ../drs-project:/usr/local/domain-api
    command: ["celery", "-A", "application", "worker", "-l", "info"]
    depends_on:
      - rabbitmq
    env_file: .env
    links:
      - rabbitmq:rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  centralnic:
    image: quay.io/heytrav/nodepp:latest
    command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "epp-centralnic.json", "-r", "centralnic-test", "--loglevel", "debug"]
    #command: ["ls", "-a", "$NODE_PATH"]
    volumes:
      - ../nodepp:/opt/project/node-epp
    links:
      - rabbitmq:rabbitmq
    depends_on:
      - rabbitmq
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  api:
    image: quay.io/heytrav/domain-api:latest
    ports:
      - "8000:8000"
    environment:
      - SQLITE_DIR=/var/domain-api/db
    volumes:
      - ../database/sqlite3:/var/domain-api/db
      - ../drs-project:/usr/local/domain-api
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - rabbitmq
      - domaindb
    env_file: .env
    links:
      - rabbitmq:rabbitmq
      - domaindb:domaindb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
