version: "2"
services:
    centralnic:
        image: nodepp:latest
        command: ["node", "./lib/node-epp-restful.js", "-j", "-f", "epp-centralnic.json", "-r", "centralnic-test", "--loglevel", "debug"]
        volumes:
            - ~/workspace/innovation/nodepp/config:/opt/project/node-epp/config
        ports:
            - "3000:3000"
    api:
        image: domain-api
        ports:
            - "8000:8000"
        volumes:
            - ~/workspace/innovation/database/sqlite3:/var/domain-api/db
            - ~/workspace/innovation/domain-api/catalystinnovation:/usr/local/domain-api/catalystinnovation
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
        env_file: .env
        links:
            - centralnic
    #data:
        #restart: "no"
        #image: postgres:latest
        #volumes:
            #- ~/workspace/innovation/database:/var/lib/postgresql/data/pgdata
            #- /var/lib/postgresql
        #env_file: .env

    #postgres:
        #restart: always
        #image: postgres:latest
        #volumes_from:
            #- data
        #ports:
            #- "5432:5432"
        #env_file: .env
