
version: "3.1"
services:
  migrate:
    command:
    - python3
    - manage.py
    - migrate
    depends_on:
    - domaindb
    deploy:
        restart_policy:
            condition: on-failure
            max_attempts: 1
    environment:
        DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
        JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
        LOGZIO_TOKEN_FILE: /run/secrets/logzio_token
        MYSQL_DATABASE_FILE: /run/secrets/mysql_database
        MYSQL_HOST: domaindb
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        MYSQL_USER_FILE: /run/secrets/mysql_user
        RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
        RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RELEASE_VERSION: 1.2.21
        SENTRY_DSN_FILE: /run/secrets/domain_api_sentry_dsn
        SENTRY_ENVIRONMENT: development
    image: quay.io/heytrav/domain-api:1.2.21
    secrets:
    - mysql_database
    - mysql_user
    - mysql_password
    - domain_api_sentry_dsn
    - django_secret_key
    - jwt_secret_key
    - logzio_token
    - rabbitmq_default_user
    - rabbitmq_default_pass
    - rabbitmq_erlang_cookie

  rabbitmq:
    environment:
        RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
        RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
    image: quay.io/heytrav/rabbitmq:latest
    ports:
    - 15672:15672
    secrets:
    - rabbitmq_default_user
    - rabbitmq_default_pass
    - rabbitmq_erlang_cookie

  celery:
    command:
    - celery
    - -A
    - application
    - worker
    - -l
    - info
    depends_on:
    - rabbitmq
    deploy:
        restart_policy:
            condition: on-failure
            delay: 10s
    environment:
        DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
        JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
        LOGZIO_TOKEN_FILE: /run/secrets/logzio_token
        MYSQL_DATABASE_FILE: /run/secrets/mysql_database
        MYSQL_HOST: domaindb
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        MYSQL_USER_FILE: /run/secrets/mysql_user
        RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
        RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RELEASE_VERSION: 1.2.21
        SENTRY_DSN_FILE: /run/secrets/celery_sentry_dsn
        SENTRY_ENVIRONMENT: development
    image: quay.io/heytrav/domain-api:1.2.21
    secrets:
    - mysql_database
    - mysql_user
    - mysql_password
    - celery_sentry_dsn
    - django_secret_key
    - jwt_secret_key
    - logzio_token
    - rabbitmq_default_user
    - rabbitmq_default_pass
    - rabbitmq_erlang_cookie

  nginx:
    command:
    - nginx
    deploy:
        restart_policy:
            condition: on-failure
            delay: 10s
    image: quay.io/heytrav/drs-nginx:0.1.0
    ports:
    - 443:443
    secrets:
    - site.key
    - site.crt

  domaindb:
    environment:
        MYSQL_DATABASE_FILE: /run/secrets/mysql_database
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        MYSQL_USER_FILE: /run/secrets/mysql_user
    image: mysql:latest
    ports:
    - 3306:3306
    secrets:
    - mysql_password
    - mysql_root_password
    - mysql_database
    - mysql_user
    volumes:
    - ../database/mysql:/var/lib/mysql

  api:
    command:
    - python3
    - manage.py
    - runserver
    - 0.0.0.0:8000
    depends_on:
    - rabbitmq
    - domaindb
    deploy:
        replicas: 1
        restart_policy:
            condition: on-failure
            delay: 10s
        update_config:
            delay: 5s
            failure_action: pause
            parallelism: 1
    environment:
        DJANGO_SECRET_KEY_FILE: /run/secrets/django_secret_key
        JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
        LOGZIO_TOKEN_FILE: /run/secrets/logzio_token
        MYSQL_DATABASE_FILE: /run/secrets/mysql_database
        MYSQL_HOST: domaindb
        MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        MYSQL_USER_FILE: /run/secrets/mysql_user
        RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
        RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RELEASE_VERSION: 1.2.21
        SENTRY_DSN_FILE: /run/secrets/domain_api_sentry_dsn
        SENTRY_ENVIRONMENT: development
    image: quay.io/heytrav/domain-api:1.2.21
    secrets:
    - mysql_database
    - mysql_user
    - mysql_password
    - domain_api_sentry_dsn
    - django_secret_key
    - jwt_secret_key
    - logzio_token
    - rabbitmq_default_user
    - rabbitmq_default_pass
    - rabbitmq_erlang_cookie
    volumes:
    - ../drs-project:/usr/local/domain-api

  cocca:
    command:
    - node
    - ./lib/rabbit-epp.js
    - -j
    - -f
    - /run/secrets/cocca_test_config
    - -r
    - cocca-test
    - --loglevel
    - debug
    depends_on:
    - rabbitmq
    deploy:
        replicas: 1
        restart_policy:
            condition: on-failure
            delay: 10s
        update_config:
            delay: 5s
            failure_action: pause
            parallelism: 1
    environment:
        EPP_LOGIN_FILE: /run/secrets/cocca_test_login
        EPP_PASSWORD_FILE: /run/secrets/cocca_test_password
        RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
        RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RELEASE_VERSION: 1.2.8
        SENTRY_DSN_FILE: /run/secrets/nodepp_sentry_dsn
    healthcheck:
        interval: 1m
        retries: 3
        test:
        - CMD
        - node
        - ./lib/healthcheck.js
        - -j
        - -f
        - /run/secrets/cocca_test_config
        - -r
        - cocca-test
        - --loglevel
        - debug
        timeout: 20s
    image: quay.io/heytrav/nodepp:1.2.8
    secrets:
    - cocca_test_login
    - cocca_test_password
    - cocca_test_config
    - nodepp_sentry_dsn
    - logzio_token
    - rabbitmq_default_user
    - rabbitmq_default_pass
    - rabbitmq_erlang_cookie
    volumes:
    - ../nodepp:/opt/project/node-epp

  memcached:
    deploy:
        resources:
            limits:
                memory: 64M
            reservations:
                memory: 64M
        restart_policy:
            condition: on-failure
            delay: 10s
    image: memcached:latest

  centralnic:
    command:
    - node
    - ./lib/rabbit-epp.js
    - -j
    - -f
    - /run/secrets/centralnic_test_config
    - -r
    - centralnic-test
    - --loglevel
    - debug
    depends_on:
    - rabbitmq
    deploy:
        replicas: 1
        restart_policy:
            condition: on-failure
            delay: 10s
        update_config:
            delay: 5s
            failure_action: pause
            parallelism: 1
    environment:
        EPP_LOGIN_FILE: /run/secrets/centralnic_test_login
        EPP_PASSWORD_FILE: /run/secrets/centralnic_test_password
        RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_default_pass
        RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_default_user
        RABBITMQ_DEFAULT_VHOST: /
        RABBITMQ_ERLANG_COOKIE_FILE: /run/secrets/rabbitmq_erlang_cookie
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RELEASE_VERSION: 1.2.8
        SENTRY_DSN_FILE: /run/secrets/nodepp_sentry_dsn
    healthcheck:
        interval: 1m
        retries: 3
        test:
        - CMD
        - node
        - ./lib/healthcheck.js
        - -j
        - -f
        - /run/secrets/centralnic_test_config
        - -r
        - centralnic-test
        - --loglevel
        - debug
        timeout: 20s
    image: quay.io/heytrav/nodepp:1.2.8
    secrets:
    - centralnic_test_login
    - centralnic_test_password
    - centralnic_test_config
    - nodepp_sentry_dsn
    - logzio_token
    - rabbitmq_default_user
    - rabbitmq_default_pass
    - rabbitmq_erlang_cookie
    volumes:
    - ../nodepp:/opt/project/node-epp



secrets:
 mysql_database: 
   external: true

 mysql_user: 
   external: true

 mysql_password: 
   external: true

 domain_api_sentry_dsn: 
   external: true

 django_secret_key: 
   external: true

 jwt_secret_key: 
   external: true

 logzio_token: 
   external: true

 rabbitmq_default_user: 
   external: true

 rabbitmq_default_pass: 
   external: true

 rabbitmq_erlang_cookie: 
   external: true

 site.key: 
   external: true

 site.crt: 
   external: true

 celery_sentry_dsn: 
   external: true

 mysql_root_password: 
   external: true

 centralnic_test_login: 
   external: true

 centralnic_test_password: 
   external: true

 centralnic_test_config: 
   external: true

 nodepp_sentry_dsn: 
   external: true

 cocca_test_login: 
   external: true

 cocca_test_password: 
   external: true

 cocca_test_config: 
   external: true

