version: "2"
services:
    centralnic:
        image: nodepp:latest
        command: ["node", "./lib/node-epp-server.js", "-j", "-f", "epp-centralnic.json", "-r", "centralnic-test"]
        volumes:
            - ~/workspace/innovation/nodepp/config:/opt/project/node-epp/config
        ports:
            - "3000:3000"
    #data:
        #restart: "no"
        #image: postgres:latest
        #volumes:
            #- ~/workspace/innovation/database:/var/lib/postgresql/data/pgdata
            #- /var/lib/postgresql
        #env_file: .env

    #postgres:
        #restart: always
        #image: postgres:latest
        #volumes_from:
            #- data
        #ports:
            #- "5432:5432"
        #env_file: .env
