version: "3.1"
services:

  rabbitmq:
    image: quay.io/heytrav/rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672
    env_file: .env

  domaindb:
    image: mariadb:10.1.21
    env_file: .env
    secrets:
      - mysql_password
      - mysql_root_password
      - mysql_database
      - mysql_user
    ports:
      - 3306:3306
    volumes:
      - ../database/mysql:/var/lib/mysql

  celery:
    image: quay.io/heytrav/domain-api:latest
    volumes:
      - ../drs-project:/usr/local/domain-api
    command: ["celery", "-A", "application", "worker", "-l", "info"]
    depends_on:
      - rabbitmq
    env_file: .env
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  centralnic:
    image: quay.io/heytrav/nodepp:latest
    command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "epp-centralnic.json", "-r", "centralnic-test", "--loglevel", "debug"]
    volumes:
      - ../nodepp:/opt/project/node-epp
    depends_on:
      - rabbitmq
    env_file: .env
    environment:
      EPP_LOGIN_FILE: /run/secrets/centralnic_test_login
      EPP_PASSWORD_FILE: /run/secrets/centralnic_test_password
    secrets:
      - centralnic_test_login
      - centralnic_test_password
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  cocca:
    image: quay.io/heytrav/nodepp:latest
    command: ["node", "./lib/rabbit-epp.js", "-j", "-f", "epp-cocca-test.json", "-r", "cocca-test", "--loglevel", "debug"]
    volumes:
      - ../nodepp:/opt/project/node-epp
    depends_on:
      - rabbitmq
    env_file: .env
    environment:
      EPP_LOGIN_FILE: /run/secrets/cocca_test_login
      EPP_PASSWORD_FILE: /run/secrets/cocca_test_password
    secrets:
      - cocca_test_login
      - cocca_test_password
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

  api:
    image: quay.io/heytrav/domain-api:latest
    ports:
      - "8000:8000"
    environment:
      - SQLITE_DIR=/var/domain-api/db
    volumes:
      - ../drs-project:/usr/local/domain-api
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - rabbitmq
      - domaindb
    env_file: .env
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s

secrets:
  cocca_test_login:
    external: true
  cocca_test_password:
    external: true
  centralnic_test_login:
    external: true
  centralnic_test_password:
    external: true
  mysql_root_password:
    external: true
  mysql_password:
    external: true
  mysql_database:
    external: true
