- name: Kill dhclient
  shell: >
           kill $(cat /var/run/dhclient-{{ ansible_default_ipv4.interface }}.pid)
  ignore_errors: true

- name: Update dhcp config
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: "request subnet-mask, broadcast-address, time-offset, routers, interface-mtu;"
    regexp: "^request "

- name: Launch dhclient (redhat)
  shell: >
           /sbin/dhclient -H {{ inventory_hostname }} -q
           -lf /var/lib/dhclient/dhclient--{{ ansible_default_ipv4.interface }}.lease
           -pf /var/run/dhclient-eth0.pid
           {{ ansible_default_ipv4.interface }}
