# Updates a host's network config so that dhclient no longer manages
# domain name parts, updates resolv.conf to have our options
# TODO move to common module, not really catalyst cloud material

# - name: Set debian facts
#   set_fact:
#     ifname: "{{ cc_dhcp_interface | default('ens3') }}"
#     pidfile: "/run/dhclient.{{ cc_dhcp_interface | default('ens3') }}.pid"
#     leasefile: "/var/lib/dhcp/dhclient.{{ cc_dhcp_interface | default('ens3') }}.leases"

- include: roles/catalystcloud/tasks/set-internal-dns-debian.yml
  when: "common_osfamily == 'debian'"

- include: roles/catalystcloud/tasks/set-internal-dns-redhat.yml
  when: "common_osfamily == 'redhat'"

#- name: Set redhat facts
#  set_fact:
#    ifname: "{{ cc_dhcp_interface | default('eth0') }}"
#    pidfile: "//var/run/dhclient-{{ ifname }}.pid"
#  when: "common_osfamily == 'redhat'"

#- apt: name=dnsmasq
