---

django_log_level: DEBUG
api_image: "quay.io/heytrav/domain-api:{{ api_version }}"
api_version: 1.2.22
nodepp_image: "quay.io/heytrav/nodepp:{{ nodepp_version }}"
nodepp_version: 1.2.8
base_directory: "{{ ansible_env.HOME }}"
sentry_environment: testing

epp_services:
  cocca: "{{ cocca_service }}"
  centralnic: "{{ centralnic_service }}"
  nzrs: "{{ nzrs_service }}"

epp_configs:
  cocca: "{{ cocca_config}}"
  centralnic: "{{ centralnic_config }}"
  nzrs: "{{ nzrs_config }}"

epp_secrets: "{{ {} | combine(nzrs_secrets, recursive=True) | combine(cocca_secrets, recursive=True) | combine(centralnic_secrets, recursive=True) }}"

volumes:
  domaindb:
    volumes:
      - /var/lib/mysql:/var/lib/mysql
