---

base_directory: /home/ubuntu
sentry_environment: testing

services:
  rabbitmq: "{{ rabbitmq_service }}" 
  domaindb: "{{ domaindb_service }}" 
  nginx: "{{ nginx_service  }}"
  memcached: "{{ memcached_service  }}"
  migrate: "{{ migrate_service  }}"
  celery: "{{ celery_service  }}"
  api: "{{ api_service  }}"
  centralnic: "{{ centralnic_service  }}"
  nzrs: "{{ nzrs_service  }}"
  cocca: "{{ cocca_service  }}"

service_volumes:
  domaindb:
    volumes:
      - /var/lib/mysql:/var/lib/mysql
