---

images:
  rabbitmq:
    image: quay.io/heytrav/rabbitmq
    tag: latest
  mariadb:
    image: mariadb
    tag: 10.1.21
  api:
    image: quay.io/heytrav/domain-api
    tag: 1.1.20
  nodepp:
    image: quay.io/heytrav/nodepp
    tag: 1.2.2
  nginx:
    image: quay.io/heytrav/drs-nginx
    tag: 0.1.0
  memcached:
    image: memcached
    tag: latest

registries:
  centralnic-test:
    ssl: true
    port: 700
    host: epp-ote.centralnic.com
    services:
      - domain
      - contact
      - host
    extensions:
      - DNSSEC
    extensionClasses:
      - extension: DNSSEC
        className: SecDnsExtension
    namespaces:
      - epp: urn:ietf:params:xml:ns:epp-1.0
        domain: urn:ietf:params:xml:ns:domain-1.0
        contact: urn:ietf:params:xml:ns:contact-1.0
        host: urn:ietf:params:xml:ns:host-1.0
        DNSSEC: urn:ietf:params:xml:ns:secDNS-1.1

rabbitmq_default_user: vault_rabbitmq_default_user
rabbitmq_default_pass: vault_rabbitmq_default_pass
rabbitmq_erlang_cookie: vault_rabbitmq_erlang_cookie

sentry_environment: testing
