---

base_directory: /home/ubuntu

images:
  rabbitmq:
    image: quay.io/heytrav/rabbitmq
    tag: latest
  mariadb:
    image: mysql
    tag: latest
  api:
    image: quay.io/heytrav/domain-api
    tag: 1.2.20
  nodepp:
    image: quay.io/heytrav/nodepp
    tag: 1.2.5
  nginx:
    image: quay.io/heytrav/drs-nginx
    tag: 0.1.0
  memcached:
    image: memcached
    tag: latest


nzrs_volumes:
sentry_environment: testing

services:
  rabbitmq: "{{ rabbitmq_service }}" 
  domaindb: "{{ domaindb_service }}" 
  nginx: "{{ nginx_service  }}"
  memcached: "{{ memcached_service  }}"
  migrate: "{{ migrate_service  }}"
  celery: "{{ celery_service  }}"
  api: "{{ api_service  }}"
  centralnic: "{{ centralnic_service  }}"
  nzrs: "{{ nzrs_service  }}"
  cocca: "{{ cocca_service  }}"

cocca_volumes:
centralnic_volumes:
domaindb_volumes:
celery_volumes:
api_volumes:
