---

base_directory: /home/ubuntu

images:
  rabbitmq:
    image: quay.io/heytrav/rabbitmq
    tag: latest
  mariadb:
    image: mysql
    tag: latest
  api:
    image: quay.io/heytrav/domain-api
    tag: 1.2.20
  nodepp:
    image: quay.io/heytrav/nodepp
    tag: 1.2.5
  nginx:
    image: quay.io/heytrav/drs-nginx
    tag: 0.1.0
  memcached:
    image: memcached
    tag: latest


cocca: true
centralnic: true
nzrs: true
nzrs_volumes:


sentry_environment: testing

celery_sentry_dsn: vault_celery_sentry_dsn
domain_api_sentry_dsn: vault_domain_api_sentry_dsn
nodepp_sentry_dsn: vault_nodepp_sentry_dsn
django_secret_key: vault_django_secret_key
jwt_secret_key: vault_jwt_secret_key
logzio_token: vault_logzio_token
rabbitmq_default_user: vault_rabbitmq_default_user
rabbitmq_default_pass: vault_rabbitmq_default_pass
rabbitmq_erlang_cookie: vault_rabbitmq_erlang_cookie
cocca_login: vault_cocca_login
cocca_password: vault_cocca_password
centralnic_login: vault_centralnic_login
centralnic_password: vault_centralnic_password
nzrs_login: vault_nzrs_login
nzrs_password: vault_nzrs_password
mysql_user: vault_mysql_user
mysql_password: vault_mysql_password
mysql_database: vault_mysql_database
site_crt: vault_site_crt
site_key: vault_site_key
nzrs_epp_pem: vault_nzrs_epp_pem
nzrs_epp_key: vault_nzrs_epp_key
