---
cc_ssh_user: ubuntu
security_group_name: "swarm-sg{{ suffix }}"
region_nameservers:
  nz-por-1: [202.78.247.197, 202.78.247.198, 202.78.247.199]
  nz_wlg_2: [202.78.240.213, 202.78.240.214, 202.78.240.215]
  nz-hlz-1: [202.78.244.85, 202.78.244.86, 202.78.244.87]

cc_default_nameservers: "{{ region_nameservers[lookup('env', 'OS_REGION_NAME')] }}"


default_security_groups:
  - {group: "{{ security_group_name }}", port: 22, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
  - {group: "{{ security_group_name }}", port: 22, remote_ip_prefix: "202.78.240.7/32"}
  
  - {group: "{{ security_group_name }}", port: 80, remote_ip_prefix: "0.0.0.0/0"}
  - {group: "{{ security_group_name }}", port: 443, remote_ip_prefix: "0.0.0.0/0"}

default_appliance_mounts:
  - { name: "docker", path: "/var/lib/docker", size: "{{ docker_partition_size | default('10000m') }}", fstype: "ext4" }

security_groups: "{{ appliance_security_groups | default(default_security_groups) }}"
appliance_default:
  flavor: "{{ cc_flavor | default(cc_default_flavor) }}"
  os_image: "{{ cc_os_image | default(cc_default_os_image) }}"
  volume_size_mb: '{{ appliance_volume_size | default(cc_default_volume_size) | int }}'
  security_groups: "default,{{ security_groups|map(attribute='group')|unique|list|join(',') }}"
  mounts: "{{ appliance_mounts | default(default_appliance_mounts) }}"

