---

suffix: "-{{ env_name }}"
ssh_remote_cidr: "{{ lookup('dig', 'myip.opendns.com', '@resolver1.opendns.com') + '/32' | default('0.0.0.0/0', true) }}"
cc_subnet_prefix: 192.168.99
cc_default_keypair_name: "swarm-key{{ suffix }}"
cc_default_keypair_pubkey_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
cc_default_keypair_pubkey: "{{ lookup('file', cc_default_keypair_pubkey_file) }}"
cc_network_name: "swarm-net{{ suffix }}"
cc_subnet_name: "swarm-subnet{{ suffix }}"
cc_router_name: "swarm-router{{ suffix }}"
cc_subnet_cidr: "{{ cc_subnet_prefix }}.0/24"
cc_subnet_dhcp_start: "{{ cc_subnet_prefix }}.98"
cc_subnet_dhcp_end: "{{ cc_subnet_prefix }}.200"
security_group_name: "swarm-sg{{ suffix }}"
cc_default_os_image: ubuntu-16.04-x86_64
cc_default_flavor: c1.c1r1
cc_ssh_user: ubuntu
cc_volume_device_name: /dev/vdb
cc_volume_group_name: data
cc_default_volume_size: 15048
cc_floating_ips: []
region_nameservers:
  nz-por-1: [202.78.247.197, 202.78.247.198, 202.78.247.199]
  nz_wlg_2: [202.78.240.213, 202.78.240.214, 202.78.240.215]
  nz-hlz-1: [202.78.244.85, 202.78.244.86, 202.78.244.87]

cc_default_nameservers: "{{ region_nameservers[lookup('env', 'OS_REGION_NAME')] }}"


default_security_groups:
  - {group: "{{ security_group_name }}", port: 22, remote_ip_prefix: "{{ ssh_remote_cidr }}"}
  - {group: "{{ security_group_name }}", port: 80, remote_ip_prefix: "0.0.0.0/0"}
  - {group: "{{ security_group_name }}", port: 443, remote_ip_prefix: "0.0.0.0/0"}

default_appliance_mounts:
  - { name: "docker", path: "/var/lib/docker", size: "{{ docker_partition_size | default('10000m') }}", fstype: "ext4" }

cc_security_groups: "{{ security_groups | default(default_security_groups) }}"
cc_security_group_names: "{{ cc_security_groups | map(attribute='group') | unique | list }}"

appliance_default:
  flavor: "{{ cc_flavor | default(cc_default_flavor) }}"
  os_image: "{{ cc_os_image | default(cc_default_os_image) }}"
  volume_size_mb: "{{ cc_default_volume_size }}"
  security_groups: "default,{{ security_group_name }}"
  mounts: "{{ appliance_mounts | default(default_appliance_mounts) }}"

