---
- name: Create network ports
  os_port:
    state: present
    admin_state_up: yes
    name: "{{ item.name }}"
    security_groups: "{{ item.security_groups }}"
    fixed_ips:
     - {ip_address: "{{ item.ip }}"}
    network: "{{ cc_network_name }}"
  with_items: "{{ cc_servers }}"

- name: Create volumes
  os_volume:
    display_name: "{{ item.name }}-data"
    size: "{{ item.volume_size_mb // 1024 }}"
  with_items: "{{ cc_servers }}"
  when: "item.volume_size_mb is defined"

- name: Create servers
  os_server:
    state: present
    name: "{{ item.name }}"
    image: "{{ item.os_image | default(cc_default_os_image) }}"
    key_name: "{{ item.keypair_name | default(cc_default_keypair_name) }}"
    flavor: "{{ item.flavor | default(cc_default_flavor) }}"
    nics:
      - port-name: "{{ item.name }}"
    volume_size: "{{ item.boot_volume_size_gb | default(omit) }}"
    security_groups: "{{ item.security_groups }}"
    auto_ip: false
    userdata: |
               #cloud-config
               users:
               - name: "{{ cc_ssh_user }}"
                 shell: /bin/bash
                 lock_passwd: true
                 sudo: ALL=(ALL) NOPASSWD:ALL
                 ssh_authorized_keys:
                     - "{{ cc_default_keypair_pubkey }}"
                 {% for key in item.authorized_keys | default(cc_default_server_authorized_keys) %}
                   - "{{ key }}"
                 {% endfor %}
               fqdn: "{{ item.name }}.{{ item.domain | default(cc_default_domain) }}"
               manage_resolv_conf: true
               resolv_conf:
                 nameservers: "{{ item.nameservers | default(cc_default_nameservers) }}"
                 searchdomains:
                   - "{{ cc_default_domain }}"
                 domain: "{{ cc_default_domain }}"
  with_items: "{{ cc_servers }}"


- name: Attach volume to server
  os_server_volume:
    volume: "{{ item.name }}-data"
    server: "{{ item.name }}"
    device: "{{ cc_volume_device_name }}"
  with_items: "{{ cc_servers }}"
  when: "item.volume_size_mb is defined"

- name: Assign floating ips
  os_floating_ip:
    state: present
    server: "{{ item.name }}"
  register: floating_ip_info
  with_items:
    - "{{ cc_servers }}"

- debug:
    var: floating_ip_info

#- name: Append floating ip to host info
  #add_host:
    #name: "{{ item.item.key }}"
    #instance_name: "{{ item.item.value.instance_name }}"
    #ansible_user: ubuntu
    #ansible_host: "{{ analytics.server.private_v4 }}"
    #ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    #groups: "analytics"
    #private_ip: "{{ analytics.server.private_v4 }}"
  #with_items: "{{ floating_ip_info.results }}"
