---
- name: Create network ports
  os_port:
    state: present
    admin_state_up: yes
    name: "{{ item.name }}"
    security_groups: "{{ item.security_groups }}"
    fixed_ips:
     - {ip_address: "{{ item.ip }}"}
    network: "{{ cc_network_name }}"
  with_items: "{{ cc_servers }}"

- name: Create volumes
  os_volume:
    display_name: "{{ item.name }}-data"
    size: "{{ item.volume_size_mb // 1024 }}"
  with_items: "{{ cc_servers }}"
  when: "item.volume_size_mb is defined"

- name: Create servers
  with_items: "{{ cc_servers }}"
  os_server:
    state: present
    name: "{{ item.name }}"
    image: "{{ item.os_image | default(cc_default_os_image) }}"
    key_name: "{{ item.keypair_name | default(cc_default_keypair_name) }}"
    flavor: "{{ item.flavor | default(cc_default_flavor) }}"
    nics:
      - port-name: "{{ item.name }}"
    volume_size: "{{ item.boot_volume_size_gb | default(omit) }}"


- name: Attach volume to server
  os_server_volume:
    volume: "{{ item.name }}-data"
    server: "{{ item.name }}"
    device: "{{ cc_volume_device_name }}"
  with_items: "{{ cc_servers }}"
  when: "item.volume_size_mb is defined"

- name: Assign floating ips
  os_floating_ip:
    state: present
    floating_ip_address: "{{ item.ip }}"
    server: "{{ item.name }}"
  with_items:
    - "{{ cc_floating_ips }}"
  when: "cc_floating_ips is defined and (cc_floating_ips | length > 0)"
