
- name: Setup manager servers
  set_fact:
    managers: "{{ managers + [ appliance_default | combine({'name': item, 'ip': hostvars[item].fixed_ip}, recursive=True)   ] }}"
  with_items: "{{ env_managers }}"

- name: Add db managers to set of managers
  set_fact:
    managers: "{{ managers + [ appliance_default | combine({'name': item, 'volume_size_mb': db.cc_volume_size, 'mounts': db.appliance_mounts, 'ip': hostvars[item].fixed_ip}, recursive=True) ] }}"
  with_items: "{{ env_db_managers }}"

- name: Setup worker servers
  set_fact:
    workers: "{{ workers + [ appliance_default | combine({'name': item, 'ip': hostvars[item].fixed_ip}, recursive=True)] }}"
  with_items: "{{ env_workers }}"

- name: Create list of servers for Catalyst Cloud
  set_fact:
    cc_servers: "{{ managers + workers }}"

- debug:
    msg: "{{ cc_servers }}" 

- name: Setup floating ips array
  set_fact:
    cc_floating_ips: "{{ cc_floating_ips + [{'name': item.name, 'ip': hostvars[item.name].ansible_host}] }}"
  with_items: "{{ cc_servers }}"

- debug:
    msg: "{{ cc_floating_ips }}"
