
- name: Setup manager servers
  set_fact:
    managers: "{{ managers + [ {'name': item, 'ip': hostvars[item].fixed_ip} | combine(manager_default_server, recursive=True)   ] }}"
  with_items: "{{ env_managers }}"

- name: Add db managers to set of managers
  set_fact:
    managers: "{{ managers + [ {'name': item, 'mounts': [database_server_mounts], 'ip': hostvars[item].fixed_ip} | combine(manager_default_server, recursive=True) ] }}"
  with_items: "{{ env_db_managers }}"

- name: Setup worker servers
  set_fact:
    workers: "{{ workers + [ {'name': item, 'ip': hostvars[item].fixed_ip} | combine(worker_default_server, recursive=True)] }}"
  with_items: "{{ env_workers }}"

- name: Create list of servers to for Catalyst Cloud
  set_fact:
    cc_servers: "{{ managers + workers }}"

- debug:
    msg: "{{ cc_servers }}" 

- name: Setup floating ips array
  with_items: "{{ cc_servers }}"
  set_fact:
    cc_floating_ips: "{{ cc_floating_ips + [{'name': item.name, 'ip': hostvars[item.name].ansible_host}] }}"

- debug:
    msg: "{{ cc_floating_ips }}"
