
- debug:
    var: appliance_default


- debug:
    var: managers 

- name: Setup manager servers
  set_fact:
    managers: "{{ managers + [ appliance_default | combine({'name': item}, recursive=True)   ] }}"
  with_items: "{{ env_managers }}"

- name: Add db managers to set of managers
  set_fact:
    managers: "{{ managers + [ appliance_default | combine({'name': item, 'volume_size_mb': db.cc_volume_size, 'mounts': db.appliance_mounts}, recursive=True) ] }}"
  with_items: "{{ env_db_managers }}"

- name: Setup worker servers
  set_fact:
    workers: "{{ workers + [ appliance_default | combine({'name': item}, recursive=True)] }}"
  with_items: "{{ env_workers }}"

- name: Create list of servers for Catalyst Cloud
  set_fact:
    cc_servers: "{{ managers + workers }}"

