---
- name: Setup gitlab servers
  set_fact:
    gitlab_servers: "{{ gitlab_servers + [{'name': item, 'ip': hostvars[item].fixed_ip} | combine(gitlab_appliance_default, recursive=True)] }}"
  with_items: "{{ groups['gitlab'] }}"

- name: Setup floating ips array
  with_items: "{{ cc_servers }}"
  set_fact:
    cc_floating_ips: "{{ cc_floating_ips + [{'name': item.name, 'ip': hostvars[item.name].ansible_host}] }}"
