---

cc_ssh_user: gitlab
cc_subnet_prefix: 10.70.0
security_group_name: drs-gitlab-sg
appliance_default:
  flavor: c1.c1r4
  os_image: "{{ cc_default_os_image }}"
  volume_size_mb: 25048
  security_groups: "default,{{ security_group_name }}"
  mounts:
    - { name: "opt", path: "/opt", size: "5000m", fstype: "btrfs" }
    - { name: "gitlab", path: "/var/lib/gitlab", size: "7000m", fstype: "btrfs" }
    - { name: "docker", path: "/var/lib/docker", size: "10000m", fstype: "ext4" }

cc_security_groups:
  - {group: "{{ security_group_name }}", port: 22, remote_ip_prefix: "{{ ssh_remote_cidr }}"}


gitlab_url: https://gitlab.catalyst.net.nz/
