---

base_directory: ~/workspace/innovation/compose-drs

cocca_volumes:
  - ../nodepp:/opt/project/node-epp
centralnic_volumes:
  - ../nodepp:/opt/project/node-epp
domaindb_volumes:
  - ../database/mysql:/var/lib/mysql
celery_volumes:
  - ../drs-project:/usr/local/domain-api
api_volumes:
  - ../drs-project:/usr/local/domain-api

sentry_environment: development

services:
  rabbitmq: "{{ rabbitmq_service }}" 
  domaindb: "{{ domaindb_service }}" 
  nginx: "{{ nginx_service  }}"
  memcached: "{{ memcached_service  }}"
  migrate: "{{ migrate_service  }}"
  celery: "{{ celery_service  }}"
  api: "{{ api_service  }}"
  cocca: "{{ cocca_service  }}"
  centralnic: "{{ centralnic_service  }}"
