---
- name: Deploy three networked host machines as swarm nodes
  hosts: localhost
  roles: [catalystcloud]
  vars:
    env_name: "staging"
  tasks:
    - name: Setup manager servers
      set_fact:
        managers: "{{ managers + [ {'name': item} | combine(manager_default_server, recursive=True)   ] }}"
      with_items: "{{ env_managers }}"

    - name: Add db managers to set of managers
      set_fact:
        managers: "{{ managers + [ {'name': item, 'mounts': [database_server_mounts]} | combine(manager_default_server, recursive=True)   ] }}"
      with_items: "{{ env_db_managers}}"

    - name: Setup worker servers
      set_fact:
        workers: "{{ workers + [ {'name': item} | combine(worker_default_server, recursive=True)] }}"
      with_items: "{{ env_workers }}"

    - name: Create list of servers to for Catalyst Cloud
      set_fact:
        cc_servers: "{{ managers + workers }}"

    - debug:
        msg: "{{ cc_servers }}" 

    - name: Setup floating ips array
      with_items: "{{ cc_servers }}"
      set_fact:
        cc_floating_ips: "{{ cc_floating_ips + [{'name': item.name, 'ip': hostvars[item.name].ansible_host}] }}"

    - debug:
        msg: "{{ cc_floating_ips }}"

    - name: Connect to Catalyst Cloud
      os_auth:


    - include: roles/catalystcloud/tasks/create-keypair.yml
    - include: roles/catalystcloud/tasks/create-security-groups.yml
    - include: roles/catalystcloud/tasks/create-servers.yml

    - name: Add newly created hosts to local ~/.ssh/config
      tags: local-changes
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        insertbefore: BOF
        block: |
          Host {{ item.name }}
              Hostname {{ hostvars[item.name].ansible_host }}
              User ubuntu
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
      with_items: "{{ cc_servers }}"

    - name: Add newly created hosts to /etc/hosts
      tags: local-changes
      become: yes
      blockinfile:
        dest: /etc/hosts
        insertafter: EOF
        block: |
          {{ hostvars[item.name]['ansible_host'] }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
      with_items: "{{ cc_servers }}"

    - wait_for:
       host: "{{ hostvars[item.name].ansible_host }}"
       port: 22
      with_items: "{{ cc_servers }}"

