---

- name: Install gitlab-runner on gitlab machine
  become: yes
  hosts: "{{ env_name }}"
  tasks:
    - name: Get os release name
      command: lsb_release -cs
      register: ubuntu_release

    - name: Add GitLab apt key
      apt_key:
        url: https://packages.gitlab.com/gpg.key
        state: present

    - name: Install GitLab Runner dependencies
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - debian-archive-keyring
        - apt-transport-https

    - name: Add GitLab Runner apt repo
      apt_repository:
        repo: 'deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/ubuntu/ {{ ubuntu_release.stdout }} main'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install GitLab Runner
      apt:
        name: gitlab-ci-multi-runner
        state: latest
        update_cache: no

    - name: Add gitlab-runner user to docker group
      user:
        name: gitlab-runner
        append: yes
        groups: docker
      notify: restart gitlab


  handlers:
    - name: restart gitlab
      systemd:
        state: restarted
        name: gitlab-runner

