---
- name: Deploy three networked host machines as swarm nodes
  hosts: localhost
  roles: [catalystcloud]
  gather_facts: true
  vars:
    env_name: "staging"
  tasks:

    - include: tasks/pre-flight-variables.yml

    - name: Connect to Catalyst Cloud
      os_auth:


    - include: roles/catalystcloud/tasks/create-keypair.yml
    - name: Create Network
      os_network:
        name: "{{ cc_network_name }}"
        state: present

    - name: Create subnet
      os_subnet:
        name: "{{ cc_subnet_name }}"
        network_name: "{{ cc_network_name }}"
        state: present
        cidr: "{{ cc_subnet_cidr }}"
        allocation_pool_start: "{{ cc_subnet_dhcp_start }}"
        allocation_pool_end: "{{ cc_subnet_dhcp_end }}"
        ip_version: 4

    - name: Create router
      os_router:
        state: present
        name: "{{ cc_router_name }}"
        network: "{{ cc_public_net_name }}"
        interfaces:
          - "{{ cc_subnet_name }}"

    - include: roles/catalystcloud/tasks/create-security-groups.yml
    - include: roles/catalystcloud/tasks/create-servers.yml

    - name: Add newly created hosts to local ~/.ssh/config
      tags: local-changes
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        insertbefore: BOF
        block: |
          Host {{ item.name }}
              Hostname {{ hostvars[item.name].ansible_host }}
              User ubuntu
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
      with_items: "{{ cc_servers }}"

    - name: Add newly created hosts to /etc/hosts
      tags: local-changes
      become: yes
      blockinfile:
        dest: /etc/hosts
        insertafter: EOF
        block: |
          {{ hostvars[item.name]['ansible_host'] }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
      with_items: "{{ cc_servers }}"

    - wait_for:
       host: "{{ hostvars[item.name].ansible_host }}"
       port: 22
      with_items: "{{ cc_servers }}"

