---
- name: Create gitlab runner host
  hosts: localhost
  roles: [catalystcloud]
  gather_facts: true
  tags:
    - provision
  tasks:
    - include: tasks/preflight-build-gitlab.yml

    - name: Connect to Catalyst Cloud
      os_auth:

    - include: tasks/cc-create-stack.yml

- name: Install python on new hosts
  hosts: "{{ env_name }}"
  become: yes
  roles: [common]
  gather_facts: false
  tags:
    - provision
    - firstonly
  tasks:
    - include: roles/common/tasks/install-python.yml
