---
- name: Deploy three networked host machines as swarm nodes
  hosts: localhost
  vars:
    suffix: "staging"
    instances:
      manager1:
        instance_name: "manager1{{ suffix }}"
        instance_group: "swarm-managers{{ suffix }}"
      worker1:
        instance_name: "worker1{{ suffix }}"
        instance_group: "swarm-workers{{ suffix }}"
      worker2:
        instance_name: "worker2{{ suffix }}"
        instance_group: "swarm-workers{{ suffix }}"
    # no changes required after this
    region: "{{ lookup('env','OS_REGION_NAME') }}"
    tasks:
