---
- name: Create gitlab runner host
  hosts: localhost
  roles: [catalystcloud]
  gather_facts: true
  vars:
    cc_network_name: trav-network
    cc_default_keypair_name: gitlab-key
    cc_subnet_name: trav-subnet
    cc_router_name: trav-router
    security_group_name: gitlab-runner-sg

  tags:
    - provision
  tasks:
    - include: tasks/preflight-build-gitlab.yml

    - name: Connect to Catalyst Cloud
      os_auth:

    - include: tasks/cc-create-stack.yml

    - name: Add newly created hosts to local ~/.ssh/config
      tags: local-changes
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        insertbefore: BOF
        block: |
          Host {{ hostvars[item.name].ansible_host }}
              User ubuntu
              StrictHostKeyChecking no
          Host {{ item.name }}
              Hostname {{ hostvars[item.name].ansible_host }}
              User ubuntu
              StrictHostKeyChecking no
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
      with_items: "{{ cc_servers }}"

    - name: Add newly created hosts to /etc/hosts
      tags: local-changes
      become: yes
      blockinfile:
        dest: /etc/hosts
        insertafter: EOF
        block: |
          {{ hostvars[item.name]['ansible_host'] }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
      with_items: "{{ cc_servers }}"

- name: Install python on new hosts
  hosts: "{{ env_name }}"
  become: yes
  roles: [common]
  gather_facts: false
  tags:
    - provision
    - firstonly
  tasks:
    - include: roles/common/tasks/install-python.yml


- name: Install docker on gitlab machine
  hosts: "{{ env_name }}"
  become: yes
  roles: [docker]

  pre_tasks:
    - name: Add entry to /etc/hosts for all instances
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item].fixed_ip }} item"
      with_items: "{{ groups[env_name] }}"

  post_tasks:
    - name: Add NZ locale to instances
      locale_gen: 
        name: en_NZ.UTF-8
        state: present

- name: Install gitlab-runner on gitlab machine
  become: yes
  hosts: "{{ env_name }}"
  tasks:
    - name: Get os release name
      command: lsb_release -cs
      register: ubuntu_release

    - name: Add GitLab apt key
      apt_key:
        url: https://packages.gitlab.com/gpg.key
        state: present

    - name: Install GitLab Runner dependencies
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - debian-archive-keyring
        - apt-transport-https

    - name: Add GitLab Runner apt repo
      apt_repository:
        repo: 'deb https://packages.gitlab.com/runner/gitlab-ci-multi-runner/ubuntu/ {{ ubuntu_release.stdout }} main'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install GitLab Runner
      apt:
        name: gitlab-ci-multi-runner
        state: latest
        update_cache: no
