# To be run exclusively for creating/updating docker configs
---
- name: Clean-up unused docker configs
  hosts: "primary_manager:&{{ env_name }}"
  tasks:

    - name: Register existing docker configs
      command: docker config ls --format  "{{ '{{' }}.Name{{  '}}' }}"
      register: existing_configs


    - name: Remove unused configs
      with_items: "{{ existing_configs.stdout_lines }}" 
      command: docker config rm "{{ item }}"
      when: item not in config_set
