---
- name: Docker stack configuration
  hosts: "primary_manager:&{{ env_name }}"
  tasks:

    - name: Create docker compose spec
      template:
        src: templates/drs-stack.yml.j2
        dest: "{{ base_directory  }}/drs-stack.yml"
      notify:
        - deploy stack
        - nodepp version
        - api version
        - celery version

  handlers:
    - name: deploy stack
      command: docker stack deploy -c  "{{ base_directory  }}/drs-stack.yml" domainapi

    - name: nodepp version
      when: nodepp_sentry_webhook_url is defined
      become: no
      run_once: yes
      local_action:
        module: uri
        url: "{{  nodepp_sentry_webhook_url }}"
        method: POST
        body_format: json
        status_code: 201, 208
        body: >
          {
            "version": "{{ images.nodepp.tag }}"
          }


    - name: api version
      when: api_sentry_webhook_url is defined
      become: no
      run_once: yes
      local_action:
        module: uri
        url: "{{  api_sentry_webhook_url }}"
        method: POST
        body_format: json
        status_code: 201, 208
        body: >
          {
            "version": "{{ images.api.tag }}"
          }


    - name: celery version
      when: celery_sentry_webhook_url is defined
      become: no
      run_once: yes
      local_action:
        module: uri
        url: "{{  celery_sentry_webhook_url }}"
        method: POST
        body_format: json
        status_code: 201, 208
        body: >
          {
            "version": "{{ images.api.tag }}"
          }
