# To be run exclusively for creating/updating docker configs
# 
# Because of the way docker config works (like docker secrets), we can't just
# change the underlying configuration and expect the application to recognise
# it, nor can we "docker config rm X &&  docker config create X" with an
# updated X. Docker will complain that the config is still in use by a
# service. Instead the idea is to create a config called myconfig-2,
# create the docker stack file with that new version and run an
# update. After the update, run "docker config rm myconfig-1".
#
# This requires setting a "version" number as part of the configuration. The
# version number itself must not have any significance for the application; it
# merely serves to tell docker config that there is a "new" configuration to
# point to. It's probably also helpful to have it appear in the actual config
# file so that ansible notices a change and notifies the handler.
---
- name: Docker stack configuration
  hosts: "primary_manager:&{{ env_name }}"
  tasks:
    - debug:
        var: cc_ssh_user

    - name: Register existing docker configs
      command: docker config ls --format  "{{ '{{' }}.Name{{  '}}' }}"
      register: existing_configs

    - name: Generate nodepp json config files
      template:
        src: templates/config.json.j2
        dest: "{{ ansible_env.HOME}}/{{ item.value.meta.file }}"
      with_dict: "{{ epp_configs }}"
      when: "'item.value.meta.name-item.value.meta.version' not in existing_configs"
      notify: "create {{ item.key }}"


    - name: Generate nginx site.conf config file
      template:
        src: templates/nginx.conf.j2
        dest: "{{ ansible_env.HOME  }}/{{ nginx_config.meta.file  }}"
      when: "'nginx_config.meta.name-nginx_config.meta.version' not in existing_configs"
      notify:
        - create nginx

  handlers:
    - name: create cocca
      command:  docker config create 'cocca-{{ cocca_config.meta.version  }}' "{{ ansible_env.HOME  }}/{{ cocca_config.meta.file  }}"

    - name: create centralnic
      command:  docker config create 'centralnic-{{ centralnic_config.meta.version  }}' "{{ ansible_env.HOME  }}/{{ centralnic_config.meta.file  }}"

    - name: create nzrs
      command:  docker config create 'nzrs-{{ nzrs_config.meta.version  }}' "{{ ansible_env.HOME  }}/{{ nzrs_config.meta.file  }}"

    - name: create nginx
      command:  docker config create 'nginx-{{ nginx_config.meta.version  }}' "{{ ansible_env.HOME  }}/{{ nginx_config.meta.file  }}"
