- name: Set name for source of config
  set_fact:
    source: "{{ service_name }}-{{ service_config.version }}"

- name: Create compose config
  set_fact:
    compose_config: 
      source: "{{ source }}"

- name: Create compose config
  set_fact:
    compose_config: "{{ compose_config | combine(service_config.compose, recursive=True ) }}"
  when: "'compose' in service_config"

- name: Add service config to existing services
  with_items: "{{ service_config.services }}"
  loop_control:
    loop_var: config_item
  include: ./append-compose-config.yml
  when: config_item in services

