---

- name: Define source
  set_fact:
    source: "{{ config.name }}-{{ config.version }}"

- name: Set default compose dict
  set_fact:
    compose_config: 
      source: "{{ source }}"

- name: Add compose from item if defined
  set_fact:
    compose_config: "{{ compose_config|combine(config.compose, recursive=True)  }}"
  when: "'compose' in config"

- name: Add source to list of configs
  set_fact:
    known_configs: "{{ known_configs + [source] }}"

- name: Add config to service
  set_fact:
    service_configs: "{{ service_configs + [compose_config]  }}"
