
# TODO Handle case where a service might have multiple configs. Currently only
# handle case where a service has exactly 1 config.
- name: Set up service config set
  set_fact:
    service_configs: []

- name: Process compose config
  include: ./load-compose-config.yml
  loop_control:
    loop_var: config_item
  vars:
    config: "{{ config_item  }}"
  with_items: "{{ epp_service_configs  }}"

- name: Create configs attribute for compose
  set_fact:
    compose_config:
      configs: "{{ service_configs  }}"

- name: Add config for "{{ service_name }}"
  set_fact:
    services: "{{ services|combine({service_name: compose_config}, recursive=True) }}"
