---
- name: Create a gitlab runner
  become: true
  hosts: "{{ env_name }}"
  tasks:

    - name: Register python test gitlab runner
      tags: 
        - pythontest1
      shell: >
        gitlab-runner register --url {{ gitlab_url }}
        --locked --tag-list docker,dr-api,python
        --description "trav-python-test-runner1"
        --registration-token {{ gitlab_registration_token }}
        --executor "docker" 
        --docker-image gitlab.catalyst.net.nz:4567/domain-registration-api/registration-api/python-test-base:v2
        --non-interactive --run-untagged=false

    - name: Register python test gitlab runner
      tags: 
        - shell1
      shell: >
        gitlab-runner register --url {{ gitlab_url }}
        --locked --tag-list docker,dr-api,shell
        --description "trav-shell-test-runner1"
        --registration-token {{ gitlab_registration_token }}
        --executor "shell" 
        --non-interactive --run-untagged=false
