---

- name: Cookbook showing loading secrets from vault
  hosts: "primary_manager:&{{ env_name }}"

  tasks:

    - name: Register existing secrets
      command: docker secret ls  --format "{{ '{{' }}.Name{{ '}}' }}"
      register: existing_secrets

    - name: Debug results
      debug:
        msg: "{{ existing_secrets }}"

    - name: add secrets to docker v1
      shell: "echo {{ item.value|quote }} | docker secret create {{ item.key|quote }} -"
      when: item.key not in existing_secrets.stdout_lines
      with_dict: "{{ secrets }}"
      no_log: True

